export const styles = {
  safe: { flex: 1, backgroundColor: "#FFFFFF" },
  flex: { flex: 1 },
  centered: {
    flex: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 12,
    padding: 24,
  },
  container: { padding: 16, gap: 16, paddingBottom: 64 },
  field: { gap: 4 },
  row: { flexDirection: "row" as const, gap: 12 },
  flexItem: { flex: 1 },
  sectionHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
  },
  checklistRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  checklistInput: { flex: 1 },
  checklistActions: { flexDirection: "row" as const, gap: 4 },
  checklistHint: { marginTop: -8 },
  formError: {
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FCA5A5",
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  conflictBanner: {
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FCD34D",
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  conflictActions: { flexDirection: "row" as const, gap: 8, flexWrap: "wrap" as const },
  submit: { marginTop: 8 },
};
