export const styles = {
  safe: { flex: 1, backgroundColor: "#FFFFFF" },
  container: { flex: 1 },
  centered: {
    flex: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 12,
    padding: 24,
  },
  search: { marginHorizontal: 16, marginTop: 12, marginBottom: 8 },
  filterRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingHorizontal: 16,
    marginBottom: 8,
    gap: 8,
  },
  chipRow: { gap: 8, paddingRight: 8 },
  listContent: { paddingHorizontal: 16, paddingBottom: 96, flexGrow: 1 },
  row: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    gap: 4,
  },
  rowHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
  },
  empty: { alignItems: "center" as const, gap: 8, padding: 24 },
  footer: { paddingVertical: 16 },
  fab: {
    position: "absolute" as const,
    right: 20,
    bottom: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  fabLabel: { fontSize: 24, lineHeight: 28 },
};
